/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/ArticleItem.vue')['default']
    ArticlesList: typeof import('./src/components/ArticlesList.vue')['default']
    ImageItem: typeof import('./src/components/ImageItem.vue')['default']
    ImageSpinner: typeof import('./src/components/ImageSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
